---
version: "3.5"
services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=911
      - PGID=911
      - TZ=Europe/Amsterdam
    volumes:
      - /data/docker/radarr:/config
      - /data/movies:/movies
      - /data/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=911
      - PGID=911
      - TZ=Europe/Amsterdam
    volumes:
      - /data/docker/sonarr:/config
      - /data/series:/tv
      - /data/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=911
      - PGID=911
      - TZ=Europe/Amsterdam
    volumes:
      - /data/docker/nzbget:/config
      - /data/downloads:/downloads
    ports:
      - 6789:6789
    restart: unless-stopped

  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=911
      - PGID=911
      - VERSION=docker
    volumes:
      - /data/docker/plex:/config
      - /data/series:/data/tvshows
      - /data/movies:/data/movies
    restart: unless-stopped

networks:
  default:
    external:
      name: my_bridge
